### ISSUE TITLE
Geolocation is unavailable for Insecure Origins

### ISSUE THREAD

**Issue by mweinelt** [vied12/nsfw#23]
When served over plain HTTP sites cannot request Geolocation anymore.

Please roll out HTTPS.

```
[Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
searchWhereIam @ f2560c74c947.js:4206
fn @ VM105:4
b @ f2560c74c947.js:761
e @ f2560c74c947.js:766
$eval @ f2560c74c947.js:761
$apply @ f2560c74c947.js:761
(anonymous) @ f2560c74c947.js:766
dispatch @ f2560c74c947.js:66
r.handle @ f2560c74c947.js:66
```

**Comment by vied12** [comment]
You're right, https would be nice, but it also mean I would have to start to pay for it...

**Comment by mweinelt** [comment]
If Letsencrypt works for you, maybe consider checking out https://github.com/certbot/certbot.

**Comment by vied12** [comment]
yeah I could use Letsencrypt but then I would have to start to pay for my hosting service, Heroku, which doesn't allow a custom domain name with https for free

**Comment by azrdev** [comment]
@vied12 seems like the official workaround for ssl on heroku free with custom domains is using Cloudflare UniversalSSL: https://twitter.com/MasteringHeroku/status/958046581432954885

**Comment by vied12** [comment]
Really cool, thanks!

**Comment by vied12** [comment]
https in now working for free, thanks to @azrdev

**Comment by azrdev** [comment]
@vied12 thx for caring! It still loads OSM tiles over http, though. I think you'd have to change your invocation of leaflet like here: https://github.com/Leaflet/Leaflet/issues/3186#issuecomment-155360520

**Comment by vied12** [comment]
Thanks it's now fixed too
