### ISSUE TITLE
Smogalarm.org is down

### ISSUE THREAD

**Issue by floelhoeffel** [vied12/nsfw#26]
Org
![screenshot_20180210-110522](https://user-images.githubusercontent.com/6864947/36060875-5179f28e-0e52-11e8-9333-b37f7ce6cba4.png)

**Comment by vied12** [comment]
oups my bad... I forgot to redirect smogalarm.org to www.smogalarm.org with cloudflare.
It's now fixed. Thanks !

**Comment by floelhoeffel** [comment]
Fantastic 👍
